replicaCount: 1

image:
  repository: ghcr.io/victor-becerra/ingress-migration-shell-operator
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  name: "ingress-migration-sa"

rbac:
  create: true
