replicaCount: 1

image:
  repository: victorbecerra/ingress-migration-shell-operator
  pullPolicy: IfNotPresent
  # Leave empty to default to the chart's appVersion.
  tag: ""

serviceAccount:
  create: true
  name: "ingress-migration-sa"

rbac:
  create: true
