apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ingress-migration
  labels:
    app: ingress-migration
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ingress-migration
  template:
    metadata:
      labels:
        app: ingress-migration
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: shell-operator
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SHELL_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: hooks
              mountPath: /hooks
      volumes:
        - name: hooks
          configMap:
            name: {{ .Release.Name }}-ingress-migration-scripts
            defaultMode: 0755
